// app/lib/sample-data.ts
import { Property, Reservation } from '@/types';

export const sampleProperties: Property[] = [
  {
    id: 1,
    address: "Kurfürstendamm 123",
    unit_number: "3A",
    floor: "3. OG",
    size_m2: 85.5,
    rooms: 3,
    total_price: 750000,
    status: "available",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"],
    project: "Berlin Mitte Residenz",
    energy_class: "A+",
    year_built: 2023,
    monthly_rent_cold: 2500,
    building_condition: "Neubau",
    asset_class: "Premium",
    heating_type: "Fußbodenheizung",
    house_fee: 250,
    commission_percent: 3.57,
    value_growth_percent: 3.5,
    rent_increase_percent: 2.0
  },
  {
    id: 2,
    address: "Prenzlauer Allee 45",
    unit_number: "12B",
    floor: "4. OG",
    size_m2: 120,
    rooms: 4,
    total_price: 1200000,
    status: "reserved",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
    project: "Prenzlauer Berg Tower",
    energy_class: "B",
    year_built: 2022,
    monthly_rent_cold: 3200,
    outdoor_space: "Balkon 12m²",
    building_condition: "Neubau",
    asset_class: "Luxury",
    heating_type: "Zentralheizung",
    house_fee: 320,
    commission_percent: 3.57,
    value_growth_percent: 4.0,
    rent_increase_percent: 2.5
  },
  {
    id: 3,
    address: "Friedrichstraße 78",
    unit_number: "PH1",
    floor: "Penthouse",
    size_m2: 200,
    rooms: 5,
    total_price: 2500000,
    status: "available",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
    project: "Friedrich Luxury Living",
    energy_class: "A",
    year_built: 2024,
    monthly_rent_cold: 5500,
    outdoor_space: "Dachterrasse 80m²",
    building_condition: "Neubau",
    asset_class: "Ultra-Luxury",
    heating_type: "Fußbodenheizung",
    house_fee: 500,
    commission_percent: 3.57,
    value_growth_percent: 5.0,
    rent_increase_percent: 3.0
  },
  {
    id: 4,
    address: "Alexanderplatz 10",
    unit_number: "5C",
    floor: "5. OG",
    size_m2: 65,
    rooms: 2,
    total_price: 520000,
    status: "sold",
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    project: "Alex Tower",
    energy_class: "B+",
    year_built: 2021,
    monthly_rent_cold: 1800,
    building_condition: "Neubau",
    asset_class: "Standard",
    heating_type: "Zentralheizung",
    house_fee: 180,
    commission_percent: 3.57,
    value_growth_percent: 3.0,
    rent_increase_percent: 2.0
  },
  {
    id: 5,
    address: "Potsdamer Platz 15",
    unit_number: "8A",
    floor: "8. OG",
    size_m2: 95,
    rooms: 3,
    total_price: 890000,
    status: "available",
    images: ["https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800"],
    project: "Potsdamer Höfe",
    energy_class: "A",
    year_built: 2023,
    monthly_rent_cold: 2800,
    outdoor_space: "Loggia 8m²",
    building_condition: "Neubau",
    asset_class: "Premium",
    heating_type: "Fußbodenheizung",
    house_fee: 280,
    commission_percent: 3.57,
    value_growth_percent: 3.8,
    rent_increase_percent: 2.2
  }
];

export const sampleReservations: Reservation[] = [
  { 
    id: 1, 
    property: "Kurfürstendamm 123, 3A", 
    property_id: 1,
    status: "Angefragt", 
    buyer: "Max Müller",
    buyer_first_name: "Max",
    buyer_last_name: "Müller",
    buyer_email: "max.mueller@email.de",
    buyer_phone: "+49 171 1234567",
    date: "2024-01-15",
    notes: "Kunde interessiert sich für Finanzierungsmöglichkeiten"
  },
  { 
    id: 2, 
    property: "Prenzlauer Allee 45, 12B", 
    property_id: 2,
    status: "Reserviert", 
    buyer: "Anna Schmidt",
    buyer_first_name: "Anna",
    buyer_last_name: "Schmidt",
    buyer_email: "anna.schmidt@email.de",
    buyer_phone: "+49 172 2345678",
    date: "2024-01-14",
    notes: "Reservierungsbestätigung versendet"
  },
  { 
    id: 3, 
    property: "Friedrichstraße 78, PH1", 
    property_id: 3,
    status: "Notarvorbereitung", 
    buyer: "Thomas Wagner",
    buyer_first_name: "Thomas",
    buyer_last_name: "Wagner",
    buyer_email: "thomas.wagner@email.de",
    buyer_phone: "+49 173 3456789",
    date: "2024-01-10",
    notar_date: "2024-02-15",
    notes: "Unterlagen beim Notar eingereicht"
  },
  { 
    id: 4, 
    property: "Alexanderplatz 10, 5C", 
    property_id: 4,
    status: "Verkauft", 
    buyer: "Julia Weber",
    buyer_first_name: "Julia",
    buyer_last_name: "Weber",
    buyer_email: "julia.weber@email.de",
    buyer_phone: "+49 174 4567890",
    date: "2024-01-05",
    notar_date: "2024-01-25",
    notes: "Kaufvertrag unterzeichnet, Zahlung erfolgt"
  },
  { 
    id: 5, 
    property: "Potsdamer Platz 15, 8A", 
    property_id: 5,
    status: "Angefragt", 
    buyer: "Michael Fischer",
    buyer_first_name: "Michael",
    buyer_last_name: "Fischer",
    buyer_email: "michael.fischer@email.de",
    buyer_phone: "+49 175 5678901",
    date: "2024-01-16",
    notes: "Besichtigungstermin vereinbart für 20.01.2024"
  }
];